      - name: Create RDP user with random password
        shell: powershell
        run: |
          $username = "clouduser"

          $chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%"

          $password = -join (
            1..18 | ForEach-Object {
              $chars[(Get-Random -Minimum 0 -Maximum $chars.Length)]
            }
          )

          $securePassword = ConvertTo-SecureString `
            $password `
            -AsPlainText `
            -Force

          if (Get-LocalUser -Name $username -ErrorAction SilentlyContinue) {
            Remove-LocalUser -Name $username
          }

          New-LocalUser `
            -Name $username `
            -Password $securePassword `
            -FullName "Cloud RDP User" `
            -Description "GitHub Actions RDP user" `
            -PasswordNeverExpires

          Add-LocalGroupMember `
            -Group "Administrators" `
            -Member $username

          Add-LocalGroupMember `
            -Group "Remote Desktop Users" `
            -Member $username

          "RDP_USERNAME=$username" | Out-File -FilePath $env:GITHUB_ENV -Append
          "RDP_PASSWORD=$password" | Out-File -FilePath $env:GITHUB_ENV -Append

          Write-Host "======================================"
          Write-Host "RDP USER"
          Write-Host "Username : $username"
          Write-Host "Password : $password"
          Write-Host "======================================"
